Добавляет разметку всех страниц
htmlacademy-adaptive/1413529-cat-energy-1 pull request #2
Opened 2023-12-03 16:05 UTC by Natali34

2023-12-05 16:52 UTC, Kartaviy-arteom requested changes

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +  <title>Католог продукции кэт энерджи</title>
тут закралась опечатка

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +    </div>
тут тебе не нужно создавать столько блоков. Будет просто logo, logo__icon. Путь у картинки нужно также подправить, ты уже в source.

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <a class="main-navigation__link" href="index.html">ГЛАВНАЯ</a>
можно в css использовать для просых трансформаций текста

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +            <b class="catalog__options catalog__options--value">700 ₽</b>
сюда подойдет список определений

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +                  просмотра.</span></a>
плюс просто декоративный

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +      <div class="contacts__map contacts__map--indicator">
а у тебя по-моему везде одинаковая карта, модификатор тебе вроде как и не нужен

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/catalog.html
> +        <p class="copyright__text">HTML Academy</p>
думаю текст тоже должен быть в ссылке

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/form.html
> +      <form class="selection-container__form" action="https://echo.htmlacademy.ru/" method="get">
method будет post

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/index.html
> +        <header class="selection__header">
думаю хедер тут избыточен

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/index.html
> +              <p class="selection__title selection__title--slim">ПОХУДЕНИЕ</p>
похоже на заголовок

2023-12-05 16:52 UTC, Kartaviy-arteom commented on source/index.html
> +      </div>
внутри слайдера

2023-12-05 20:51 UTC, Natali34 commented on source/catalog.html
> +  <title>Католог продукции кэт энерджи</title>
поправила

2023-12-05 21:07 UTC, Natali34 commented on source/catalog.html
> +                  просмотра.</span></a>
удалила строку, пропишу плюс с помощью стилей

2023-12-05 21:17 UTC, Natali34 commented on source/index.html
> +              <p class="selection__title selection__title--slim">ПОХУДЕНИЕ</p>
поправила

2023-12-06 12:33 UTC, Natali34 commented on source/catalog.html
> +            <a class="main-navigation__link" href="index.html">ГЛАВНАЯ</a>
поправила

2023-12-06 12:33 UTC, Natali34 commented on source/catalog.html
> +    </div>
создала 1 блок logo

2023-12-06 12:33 UTC, Natali34 commented on source/form.html
> +      <form class="selection-container__form" action="https://echo.htmlacademy.ru/" method="get">
поправила

2023-12-06 12:33 UTC, Natali34 commented on source/catalog.html
> +        <p class="copyright__text">HTML Academy</p>
поправила

2023-12-06 12:34 UTC, Natali34 commented on source/index.html
> +        <header class="selection__header">
удалила header

2023-12-06 12:36 UTC, Natali34 commented on source/index.html
> +      </div>
блок slider-range перенесла в внутрь слайдера

2023-12-06 12:40 UTC, Natali34 commented on source/catalog.html
> +      <div class="contacts__map contacts__map--indicator">
Я модификатор прописала, чтобы была возможность стилизовать карту по расположению  на сайте (отступы...). Модификатор убрала

2023-12-06 17:40 UTC, merged