Векторная графика и оптимизация
htmlacademy-adaptive/1413529-cat-energy-1 pull request #7
Opened 2024-06-20 16:48 UTC by Natali34

2024-06-20 18:25 UTC, Kartaviy-arteom requested changes

2024-06-20 18:25 UTC, Kartaviy-arteom commented on source/catalog.html
> +              <source media="(min-width: 768px)" srcset="img/icons/icon-plus-tablet.svg" width="60" height="60">
svg + use из спрайта. И нужно ли здесь два изображения плюса?

2024-06-20 18:25 UTC, Kartaviy-arteom commented on source/img/icons/advantage-clock-mob@1x.png
это иконка svg и остальные на зеленом фоне.  Они не нужны в двух экземплярах и соберутся в спрайт

2024-06-20 18:25 UTC, Kartaviy-arteom commented on source/sass/blocks/main-navigation.scss
> +    // width: 436px;
закоментированный код нужно будет удалить

2024-06-20 18:25 UTC, Kartaviy-arteom commented on source/sass/global/fonts.scss
> +  font-weight: 400;
font-weight: 400; должен быть другой у medium(500)

2024-06-20 18:56 UTC, Natali34 commented on source/sass/blocks/main-navigation.scss
> +    // width: 436px;
удалила

2024-06-20 19:39 UTC, Natali34 commented on source/catalog.html
> +              <source media="(min-width: 768px)" srcset="img/icons/icon-plus-tablet.svg" width="60" height="60">
поправила, здесь не нужно два изображения плюса

2024-06-20 20:35 UTC, Natali34 commented on source/img/icons/advantage-clock-mob@1x.png
поправила

2024-06-21 05:56 UTC, Kartaviy-arteom approved these changes

2024-06-21 05:56 UTC, merged